### ISSUE TITLE
Not sure how to set up for MythTV 0.28

### ISSUE THREAD

**Issue by bennettpeter** [garybuhrmaster/tv_grab_na_sd#2]
I do not know what the dependencies are for installing this.

Running it the first time gives the error Can't locate Digest/SHA1.pm. there is no Ubuntu repository with that file. 
There are these possibilities
- /usr/lib/parrot/6.6.0/tools/lib/Parrot/SHA1.pm 	parrot-devel
- /usr/share/perl5/CGI/Application/Plugin/Authentication/Driver/Filter/sha1.pm 	libcgi-application-plugin-authentication-perl
- /usr/share/perl5/Crypt/PBKDF2/Hash/HMACSHA1.pm 	libcrypt-pbkdf2-perl
- /usr/share/perl5/Digest/HMAC_SHA1.pm 	libdigest-hmac-perl
- /usr/share/perl5/Mail/DKIM/Algorithm/dk_rsa_sha1.pm 	libmail-dkim-perl
- /usr/share/perl5/Mail/DKIM/Algorithm/rsa_sha1.pm 	libmail-dkim-perl
- /usr/share/perl5/Net/OAuth/SignatureMethod/HMAC_SHA1.pm 	libnet-oauth-perl
- /usr/share/perl5/Net/OAuth/SignatureMethod/RSA_SHA1.pm 	libnet-oauth-perl

Should I use cpan? I normally try to stay within the system repositories when installing modules.

Once I get this one installed there will likely be many others.

**Comment by garybuhrmaster** [comment]
In debian, one should be careful about installing cpan modules (at least into system libraries, into private space should be fine).  In this particular case, sha1 was chosen by Schedules Direct for their password hash function, so sha1 has to be used, but debian decided to drop support for the sha1 (only) perl digest libraries and now ships only an extended SHA digest library that includes additional hash capabilities (not useful to this grabber, but in the package), even though most other distros still ship the sha1 (only) digest library in addition to the extended library for compatibility with existing code (and there is a lot of existing code in the wild).  I'll look into using the alternative library if it is also available on other distros (which will require some research).

**Comment by bennettpeter** [comment]
Thanks for the answer. I did install into a private library using cpan, and I managed to configure and run, after installing a number of other modules. The grabber worked well once I got it configured. I did not yet import the xml file into mythtv.

**Comment by garybuhrmaster** [comment]
Repo updated to use perl Digest::SHA rather than Digest::SHA1
